version: '3.9'
services:
  react-app:
    build: .
    ports:
      - "5101:80"
    container_name: kritikabhachawat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s